[general]
brewery_name = "BRYGGANS BRYGGERI BÄRS BB"

[control]
offset_on = 1.0
offset_off = 0.0

[hardware]
  sensors = [
  ]
  actors = [
    {id = "mash_tun", gpio_pin = 13},
    {id = "kettle", gpio_pin = 16}
  ]
