[general]
brewery_name = "BRYGGANS BRYGGERI BÄRS BB"
log_level = "Debug"

[control]
offset_on = 1.0
offset_off = 0.0

[hardware]
  sensors = [
    {id = "mash_tun", address = "28-0416802230ff"},
    {id = "kettle", address = "28-041680223000"}
  ]
  actors = [
    {id = "mash_tun", gpio_pin = 13},
    {id = "kettle", gpio_pin = 16}
  ]

[nats]
  bin_path = "target/nats-server"
  config = "./nats-config.yaml"
  server = "localhost"
  user = "jackonelli"
  pass = "penna1glas"
