# Nice intro to cargo-make
# https://medium.com/@sagiegurari/automating-your-rust-workflows-with-cargo-make-part-5-final-predefined-tasks-ci-support-and-4594812e57da
[tasks.docs]
description = "Generate bryggIO documentation."
command = "cargo"
args = ["doc", "--no-deps"]

[tasks.rbpi-build]
description = "Build for RbPi (armv7-target)"
command = "cargo"
args = ["build", "--target=armv7-unknown-linux-gnueabihf"]

[tasks.build]
description = "Build for RbPi (armv7-target)"
command = "cargo"
args = ["build"]
