[tasks.docs]
description = "Generate BryggIO documentation."
command = "cargo"
args = ["doc", "--no-deps"]

[tasks.build]
description = "Build targets: bryggio-supervisor, bryggio-sensor-box and bryggio-cli"
command = "cargo"
args = ["build"]

[tasks.rbpi-build]
env = { "CC_armv7_unknown_linux_musleabihf" = "arm-linux-gnueabihf-gcc" }
description = "Build all targets for RbPi (armv7-target)"
command = "cargo"
args = ["build", "--target=armv7-unknown-linux-musleabihf"]

[tasks.rbpi-check]
env = { "CC_armv7_unknown_linux_musleabihf" = "arm-linux-gnueabihf-gcc" }
description = "Check all targets for RbPi (armv7-target)"
command = "cargo"
args = ["check", "--target=armv7-unknown-linux-musleabihf"]

[tasks.rbpi-install-supervisor]
description = "Copy supervisor to RbPi (armv7-target)"
dependencies = ["rbpi-build"]
script = [
  "scp target/armv7-unknown-linux-gnueabihf/debug/bryggio-supervisor pi_louron:~/bryggio",
]

[tasks.rbpi-install-cli]
description = "Copy CLI to RbPi (armv7-target)"
dependencies = ["rbpi-build"]
script = [
  "scp target/armv7-unknown-linux-gnueabihf/debug/bryggio-cli pi_louron:~/bryggio",
]

[tasks.rbpi-install]
description = "Copy all targets and config to RbPi (armv7-target)"
dependencies = ["rbpi-install-supervisor", "rbpi-install-cli"]
