[general]
brewery_name = "My brewery"
log_level = "Debug"

[control]
offset_on = 1.0
offset_off = 0.0

[hardware]
  sensors = [
    {id = "mash_tun", address = "28-0416802230ff"},
    {id = "kettle", address = "28-041680223000"}
  ]
  actors = [
    {id = "mash_tun", gpio_pin = 13},
    {id = "kettle", gpio_pin = 16}
  ]

[nats]
  bin_path = "<path_to_nats_server_binary>"
  server = "<ip>"
  user = "<username>"
  pass = "<password>"
