[package]
name = "bryggio-server"
version = "0.1.0"
authors = ["Jakob <jakob.lindqvist@chalmers.se>"]
edition = "2018"

[dependencies]
rocket = ">=0.4.2"
rocket_contrib = ">=0.4.2"
rocket_cors = "0.5.0"
bryggio-lib = { path = "../lib" }
