[package]
name = "bryggio-core"
version = "0.2.0"
authors = ["Jacko Jackonelli <jakob.lindqvist.92@gmail.com>"]
edition = "2021"

[dependencies]
embedded-hal = "=1.0.0"
rand = ">=0.8"
rand_distr = ">=0.4"
serde = { version = ">=1.0", features = ["derive"] }
serde_json = ">=1.0"
pid = ">=4"
derive_more = { version = ">=1", features = ["display", "add"] }
thiserror = ">=1.0"

[target.'cfg(target_arch = "arm")'.dependencies]
gpio-cdev = "0.6.0"
linux-embedded-hal = { version = "0.4.0", features = ["gpio_cdev"] }

[target.'cfg(target_arch = "aarch64")'.dependencies]
gpio-cdev = "0.6.0"
linux-embedded-hal = { version = "0.4.0", features = ["gpio_cdev"] }

[dev-dependencies]
assert_approx_eq = ">=1.1"
